# Generated by Django 5.0.6 on 2024-07-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='pergunta',
            field=models.TextField(),
        ),
    ]
