# Generated by Django 5.0.6 on 2024-07-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0002_alter_perguntas_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntas',
            name='pergunta_index',
        ),
    ]
