# Generated by Django 5.0.6 on 2024-07-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0003_remove_perguntas_pergunta_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='pergunta_index',
            field=models.TextField(blank=True, null=True),
        ),
    ]
